name: Procesar reuniones proyectos

on:
  push:
    paths:
      - "input/Reuniones.xlsx"

jobs:

  procesar:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pandas openpyxl

      - name: Ejecutar procesamiento
        run: |
          python scripts/procesar_datos.py

      - name: Guardar resultados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/*.xlsx
          git diff --cached --quiet || git commit -m "Actualizar resultados reuniones"
          git push
